#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $ASKLORA_USER WITH PASSWORD '$ASKLORA_PASSWORD';
    CREATE DATABASE $ASKLORA_DB;
    GRANT ALL PRIVILEGES ON DATABASE $ASKLORA_DB TO $ASKLORA_USER;
EOSQL

# ASKLORA_TEST_DB='ASKLORA_test'
# ASKLORA_TEST_USER='ASKLORA_test'
# ASKLORA_TEST_PASSWORD='ASKLORA_test'

# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
#     CREATE USER $ASKLORA_TEST_USER WITH PASSWORD '$ASKLORA_TEST_PASSWORD';
#     CREATE DATABASE $ASKLORA_TEST_DB;
#     GRANT ALL PRIVILEGES ON DATABASE $ASKLORA_TEST_DB TO $ASKLORA_TEST_USER;
# EOSQL
